import type { GearRecommendationMode, GearRecommendationProfile } from "./gearTypes";

export const gearRecommendationProfiles: Record<GearRecommendationMode, GearRecommendationProfile> = {
  dungeon_craft_only: {
    id: "dungeon_craft_only",
    labelKo: "던전 + 제작만",
    descriptionKo: "레이드를 제외하고 현재 시즌 던전, 제작, 위대한 금고 후보만 봅니다.",
    allowedSources: ["dungeon", "craft", "great_vault"],
    allowRaid: false,
    allowDungeon: true,
    allowCraft: true,
    allowGreatVault: true,
    allowDelve: false,
    preferCrafting: false,
    prioritizeTrinkets: false,
    contentFocus: "mythic_plus",
    fightStyle: "mixed",
    hideLowConfidence: true,
  },
  dungeon_craft_raid: {
    id: "dungeon_craft_raid",
    labelKo: "던전 + 제작 + 레이드",
    descriptionKo: "던전, 제작, 레이드 후보를 함께 비교합니다.",
    allowedSources: ["dungeon", "craft", "great_vault", "raid"],
    allowRaid: true,
    allowDungeon: true,
    allowCraft: true,
    allowGreatVault: true,
    allowDelve: false,
    preferCrafting: false,
    prioritizeTrinkets: false,
    contentFocus: "balanced",
    fightStyle: "mixed",
    hideLowConfidence: true,
  },
  no_raid: {
    id: "no_raid",
    labelKo: "레이드 제외",
    descriptionKo: "모든 레이드 출처를 제외하고 현실적인 비레이드 후보를 봅니다.",
    allowedSources: ["dungeon", "craft", "great_vault", "catalyst", "vendor", "delve"],
    allowRaid: false,
    allowDungeon: true,
    allowCraft: true,
    allowGreatVault: true,
    allowDelve: true,
    preferCrafting: false,
    prioritizeTrinkets: false,
    contentFocus: "mythic_plus",
    fightStyle: "mixed",
    hideLowConfidence: true,
  },
  all_sources: {
    id: "all_sources",
    labelKo: "전체",
    descriptionKo: "검증된 모든 출처를 비교합니다.",
    allowedSources: ["dungeon", "craft", "great_vault", "raid", "catalyst", "vendor", "delve"],
    allowRaid: true,
    allowDungeon: true,
    allowCraft: true,
    allowGreatVault: true,
    allowDelve: true,
    preferCrafting: false,
    prioritizeTrinkets: false,
    contentFocus: "balanced",
    fightStyle: "mixed",
    hideLowConfidence: true,
  },
  craft_priority: {
    id: "craft_priority",
    labelKo: "제작 우선",
    descriptionKo: "운에 덜 기대는 제작 후보에 가중치를 둡니다.",
    allowedSources: ["dungeon", "craft", "great_vault"],
    allowRaid: false,
    allowDungeon: true,
    allowCraft: true,
    allowGreatVault: true,
    allowDelve: false,
    preferCrafting: true,
    prioritizeTrinkets: false,
    contentFocus: "mythic_plus",
    fightStyle: "mixed",
    hideLowConfidence: true,
  },
  trinket_priority: {
    id: "trinket_priority",
    labelKo: "장신구 우선",
    descriptionKo: "장신구 후보와 관련 파밍 루트를 먼저 봅니다.",
    allowedSources: ["dungeon", "craft", "great_vault"],
    allowRaid: false,
    allowDungeon: true,
    allowCraft: true,
    allowGreatVault: true,
    allowDelve: false,
    preferCrafting: false,
    prioritizeTrinkets: true,
    contentFocus: "mythic_plus",
    fightStyle: "mixed",
    hideLowConfidence: true,
  },
};

export function gearProfile(mode: GearRecommendationMode) {
  return gearRecommendationProfiles[mode] || gearRecommendationProfiles.dungeon_craft_only;
}
